### ISSUE TITLE
Teria como fazer um tutorial de como dar upload dessa api no Heroku

### ISSUE THREAD

**Issue by fgalmeida** [ErickCReis/Proffy#7]
Faz um tempo que to querendo upar ela, mas de jeito nenhum consigo!

**Comment by ErickCReis** [comment]
@fgalmeida  talvez consiga te ajudar, está travado em qual etapa? Pode compartilhar seu projeto?

**Comment by fgalmeida** [comment]
Ja crio um repositório e mando o link

**Comment by fgalmeida** [comment]
> @fgalmeida talvez consiga te ajudar, está travado em qual etapa? Pode compartilhar seu projeto?

https://github.com/fgalmeida/Api

**Comment by fgalmeida** [comment]
> @fgalmeida talvez consiga te ajudar, está travado em qual etapa? Pode compartilhar seu projeto?

no caso em dou o deploy no heroku mas chega lá dá um erro

**Comment by fgalmeida** [comment]
@ErickCReis consegui mano kkk, acredito que tenha sido erro no procfile, mas obrigado pelo interesse em me ajudar!
